version: "3.8"
services:
  postgresql:
    image: postgres:16.2
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .db.env
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    ports:
      - "5050:80"
    env_file:
      - .db.env
    volumes:
      - ./data/pgadmin/:/var/lib/pgadmin
    user: "root"

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: nest-postgres
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "5000:5000" #웹소켓 포트
    depends_on:
      - postgresql
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  redis:
    image: redis
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASS"
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

